name: CD to Render

on:
  workflow_dispatch:  # Manual trigger for first test
  schedule:
    - cron: '*/10 * * * *'  # Every 10 mins (optional, can remove if not needed)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"
